name: test cicd git
on: [push]
jobs:
  build-testing-super:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd client && npm i
      - run: cd client && npm run build
      - run: cd client && npm run start
